itsmurfs_techblog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'itsmurfs_techblog.views.home', name='home'),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('techblog.urls')),

)

techblog/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',

    url(r'^$', 'techblog.views.home', name='home'),
    url(r'tag/(?P<tag_slug>\w+)/$', 'techblog.views.home', name='home'),
    url(r'author/(?P<author_id>\d*)/(?P<username>\w*)$', 'techblog.views.home', name='home'),
    url(r'entry-detail/(?P<entry_id>\w*)/(?P<slug>\w*)', 'techblog.views.entry_detail', name='entry_detail'),
    url(r'draft-entry-detail/(?P<entry_id>\w*)', 'techblog.views.draft_entry_detail', name='draft_entry_detail'),

    url(r'authors/', 'techblog.views.authors', name='authors'),
    url(r'about/', 'techblog.views.about', name='about')




)

if settings.DEBUG:
    #this works only in debug mode to serve uploaded files in the development server.
    # https://docs.djangoproject.com/en/dev/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns = urlpatterns +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techblog/models.py
# Create your models here.
from HTMLParser import HTMLParseError
from django.contrib.auth.models import User

from django.db import models


# Create your models here.
from djangotoolbox.fields import EmbeddedModelField, ListField
import shutil
from taggit.models import Tag

from crossdb_utils.models import EntryTagsCrossDb
from itsmurfs_techblog.settings import FILE_UPLOAD_DIRECTORY, MEDIA_ROOT, FILE_UPLOAD_TEMP_DIRECTORY, FRONT_IMAGE_SIZES, \
    MEDIA_URL, SITE_DOMAIN
from mongoadminforms.fields import SimpleListFormField

from techblog.html_utils import HtmlTool
from mongoadminforms.models import ListEmbeddedModelFieldWithForm, ListFieldWithForm, ListFieldWithSimpleForm

import PIL.Image
import os.path



class Entry(models.Model):

    PUBLISHED_STATUS = 'pub'
    DRAFT_STATUS = 'draft'

    STATUS_CHOICES = ((PUBLISHED_STATUS,'published'), (DRAFT_STATUS,'draft'))

    title = models.CharField(max_length=100, unique=True)  # inserted by: user

    meta_description = models.CharField(max_length=255, verbose_name="summary")  # inserted by: user

    content = models.TextField()  # inserted by: user

    creation_date = models.DateField(auto_now_add=True)  # automatic

    wordcount = models.IntegerField()  # automatic

    # this field contains thee cross database foreign keys to user table
    author_ids = ListField(null=True) # automatic

    # this field is the cross database foreign key to user table
    modified_by_id = models.IntegerField(null=True) # automatic

    modification_date = models.DateField(auto_now=True)  # automatic


    @property # thanks to http://stackoverflow.com/questions/6618002/python-property-versus-getters-and-setters
    def authors(self):
        #Cross db query
        usr_ids = [x for x in self.author_ids]
        return User.objects.filter(pk__in=usr_ids)

    @authors.setter
    def authors(self, value):

        #First of all initialize the author_ids list field:
        if not self.author_ids:
            self.author_ids = []

        if isinstance(value, list):
            for u in value:
                if isinstance(u, User):
                    self.author_ids.append(u.id)
                elif isinstance(u, int):
                    self.author_ids.append(u)
                else:
                    raise TypeError("Authors must be a list of User, found {}".format(type(u)))
        else:
            raise TypeError("Authors must be a list of User, found {}".format(type(value)))


    @property # thanks to http://stackoverflow.com/questions/6618002/python-property-versus-getters-and-setters
    def modified_by(self):
        #Cross db query
        return User.objects.get(pk=self.modified_by_id)

    @modified_by.setter
    def modified_by(self, value):
        if isinstance(value, User):
            self.modified_by_id = value.id
        elif isinstance(value, int):
            self.modified_by_id = value
        else:
            raise TypeError()


    @property
    def tags(self):
        #Cross db query with taggit
        #If a DoesNotExists will be raised then something wrong is happened during insertion.
        return EntryTagsCrossDb.objects.get(id_entry=self.id).tags

    @property
    def tags_list(self):
        """
        Convenient method to retrieve always a list of tags even when the entry is in drafted state.
        In this way it doesn't need to check the status of the entry outside the entry for retrieve the tags list
        """
        if self.status == Entry.PUBLISHED_STATUS:
            return self.tags.all()
        elif self.status == Entry.DRAFT_STATUS:
            return [Tag(name=t, slug=t) for t in self.drafted_tags]

    def similar_entries(self):
        #TODO Use dynamic query
        return [e.entry for e in self.tags.similar_objects()]

    @classmethod
    def get_tagged_entries(cls, tagged_items):

        p = None

        for count, e in enumerate(tagged_items.all()):
            if count==0:
                p = Q(id=e.content_object.id_entry)
            else:
                p = p | Q(id=e.content_object.id_entry)

        return Entry.objects.filter(p)

    #This fields is used to store temporarily the tags without creating the Taggit object
    #We have to do this in order to preserve the integrity and the security of the tag clouds
    #Indeed if we made the Taggit objects also for the drafted entries we would have incoherent data between the
    #entries displayed and the number of entry with a certain tags.
    drafted_tags = ListField()

    #Like tags but these will be only inserted inside meta-keywords head metatag. These should be a collection of
    #most probably searched keyword.
    seo_keywords = ListFieldWithSimpleForm(blank=True)

    slug = models.SlugField()  # automatic

    #This will be saved in mongo as a string containing the full path
    front_image = models.ImageField(upload_to=FILE_UPLOAD_TEMP_DIRECTORY, null=True)  # inserted by: user if not get the content's first image

    demo_attachment = models.URLField(blank=True, null=True)  # inserted by: user

    git_link = models.URLField(blank=True, null=True)  # inserted by: user

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=DRAFT_STATUS)

    #parsed from content, show as readonly in admin form
    references = ListEmbeddedModelFieldWithForm(EmbeddedModelField('Reference'), blank=True, null=True)

    #parsed from content when the form is submitted
    code_snippets = ListEmbeddedModelFieldWithForm(EmbeddedModelField('CodeSnippet'), blank=True, null=True)

    #see https://docs.djangoproject.com/en/1.6/ref/models/instances/#django.db.models.Model.get_absolute_url
    def get_absolute_url(self):
        """
        this is the permalink
        """
        from django.core.urlresolvers import reverse
        if self.status == Entry.PUBLISHED_STATUS:
            return reverse('entry_detail', kwargs={'entry_id': self.id, 'slug':""})
        elif self.status == Entry.DRAFT_STATUS:
            return reverse('draft_entry_detail', kwargs={'entry_id': self.id})

    def _generate_front_image_sized_name(self, original_file_name, size):
        fileName, fileExtension = os.path.splitext(original_file_name)
        size_str = "{}x{}".format(size[0], size[1])
        new_file_name = "{filename}-{size}{ext}".format(filename=fileName,
                                                        size=size_str,
                                                        ext=fileExtension)
        return new_file_name

    def _generate_resized_front_image(self, img, new_directory, original_file_name):

        if FRONT_IMAGE_SIZES:
            for social, size in FRONT_IMAGE_SIZES:
                rimg = img.resize(size)
                new_file_name = self._generate_front_image_sized_name(original_file_name, size)

                rimg.save(os.path.join(new_directory, new_file_name))

    def _get_upload_path(self):
        return os.path.join(MEDIA_ROOT,FILE_UPLOAD_DIRECTORY, self.id)

    def _get_upload_url(self):
        return os.path.join(SITE_DOMAIN,MEDIA_URL[1:],FILE_UPLOAD_DIRECTORY, self.id)

    def get_front_images(self):
        if FRONT_IMAGE_SIZES and self.front_image:
            front_images = {}
            for social, size in FRONT_IMAGE_SIZES:
                original_file_name = os.path.basename(self.front_image.name)
                image_name = self._generate_front_image_sized_name(original_file_name, size)
                front_images[social] = os.path.join(self._get_upload_url(),'front_image', image_name)
            #add the original image
            front_images['original'] = unicode(self.front_image)
            return front_images
        else:
            return None

    def insert_front_image(self, in_memory_image):
        """
        This method provides the capability of saving the front image inserted by the user in different
        size. One for each social network or other content sharing provided. It uses pillow to resize the image.
        It stores the images resized as long as the original image in the personal directory of the entry.
        """

        img = PIL.Image.open(in_memory_image)
        new_directory = os.path.join(self._get_upload_path(), "front_image")
        original_file_name = "".join(os.path.basename(in_memory_image.name).split())
        new_path = os.path.join(new_directory, original_file_name)


        if not os.path.exists(new_directory):
            os.makedirs(new_directory)
        else:
            #https://docs.python.org/2/library/shutil.html#shutil.rmtree
            shutil.rmtree(new_directory)
            os.makedirs(new_directory)

        img.save(new_path)

        self.front_image = os.path.join(self._get_upload_url(), "front_image",original_file_name)

        self._generate_resized_front_image(img, new_directory, original_file_name)



    def has_references(self):

        return bool([ref.link for ref in self.references if ref.link!=''])


    def process_html(self):
        """
        This method elaborate the content of thi entry in order to apply pygments to each tag div with class code

        :return:
        """

        try:
            html_parser = HtmlTool(self.content)
        except HTMLParseError:
            return False


        #A list of couple (code_pyg_div, data_attrs_as_dict)
        codes_to_model = html_parser.apply_pygments_to_code_tags()

        #get the content parsed with the modification applied by apply_pygments_to_code_tags
        self.content = html_parser.get_html_parsed_as_string()

        return codes_to_model

    def save(self, *args, **kwargs):

        self.title = self.title.title()

        super(Entry, self).save(*args, **kwargs)


    def __unicode__(self):

        return self.title


class CodeSnippet(models.Model):
    code = models.TextField()  # inserted by: user

    # inserted by: user with a listbox whose values must be compatible with pygments
    language = models.CharField(max_length=255)

techblog/forms.py
import re
from django.core.exceptions import ValidationError
from taggit.forms import TagField




class MyTagField(TagField):

    def __init__(self, *args, **kwargs):
        super(MyTagField, self).__init__(*args, **kwargs)

        self.validators.append(self.check_for_dash)

    def clean(self, value):
        cleaned_value = super(MyTagField, self).clean(value)

        upper_cleaned_value = []
        for v in cleaned_value:
            upper_cleaned_value.append(v.lower())


        return  upper_cleaned_value


    def check_for_dash(self, values):
        #TODO with Django 1.7 use RegexValidator with inverse_match=True
        for value in values.split(','):
            #This regex disallow all the special characters except the dot.
            #To allows more special chars add a ^\<specialchar> inside the first []
            #To disallows other things to be added you have to add a regex on the right side of the | (like [_]
            if re.search(r'[^\w^\.]|[_]', value):
                raise ValidationError("Enter a valid 'tag' consisting of one single word with only letters and numbers.")

techblog/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from taggit.models import Tag
from itsmurfs_techblog.models import Smurf
from techblog.models import Entry
from django.db.models import Min, Max, Count
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from taggit.models import Tag
from django.db.models import Q


 # https://docs.djangoproject.com/en/dev/topics/pagination/
def build_paginator(entries, request, entry_per_page):
    paginator = Paginator(entries, entry_per_page)
    page = request.GET.get('page')
    try:
        paginated_entries = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        paginated_entries = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        paginated_entries = paginator.page(paginator.num_pages)
    return paginated_entries



def home(request, tag_slug=None, author_id=None, **kwargs):

    if(tag_slug):
        #The tag page
        tag = get_object_or_404(Tag,slug=tag_slug)
        #We don't need to filter for entry.status because only the published entries have tags
        #entries = [ e.content_object.entry for e in tag.taggit_taggeditem_items.all()]
        entries = Entry.get_tagged_entries(tag.taggit_taggeditem_items)

        authors = User.objects.exclude(smurf__isnull=True)
    elif author_id:
        entries = Entry.objects.filter(author_ids=int(author_id)).filter(status=Entry.PUBLISHED_STATUS)
        authors = [User.objects.get(pk=author_id)] #the home accepts a list of author
    else:
        #The home
        entries = Entry.objects.filter(status=Entry.PUBLISHED_STATUS)
        authors = User.objects.exclude(smurf__isnull=True)

    entries = entries.order_by('-creation_date')

    paginated_entries = build_paginator(entries, request, 5)

    tag_cloud = build_tag_cloud()



    return render(request, 'techblog/home.html', {'paginated_entries':paginated_entries,
                                                  'authors':authors,
                                                   'tag_cloud': tag_cloud})


def build_tag_cloud():

    min=1 #font min size class
    max=5 #font max size class

    #Comput max and min number of items tagged by a tag and store it inside a dict
    #the keys are num_items__min and num_items__max
    annotated_tags=Tag.objects.annotate(num_items=Count('taggit_taggeditem_items')).filter(num_items__gt=0)
    min_max_items_tagged = annotated_tags.aggregate(Max('num_items'),Min('num_items'))

    tag_cloud = []
    for tag in annotated_tags:
        cloud_item = {}
        cloud_item['name'] = tag.name
        cloud_item['num_items'] = tag.num_items
        cloud_item['slug'] = tag.slug

        if tag.num_items == min_max_items_tagged['num_items__min']:
            cloud_item['size_class'] = tag.num_items
        else:
            size_class =(tag.num_items/min_max_items_tagged['num_items__max']) * (max - min) + min
            cloud_item['size_class']=size_class

        tag_cloud.append(cloud_item)

    return tag_cloud



def entry_detail(request, entry_id, slug):
    entry = get_object_or_404(Entry, pk=entry_id)
    if not entry.status == Entry.PUBLISHED_STATUS:
        raise Http404

    tag_cloud = build_tag_cloud()
    latest_entries = Entry.objects.filter(status=Entry.PUBLISHED_STATUS).order_by('-creation_date')
    front_images = entry.get_front_images()
    return render(request, 'techblog/entry_detail.html', {'entry':entry,
                                                          'latest_entries': latest_entries,
                                                          'tag_cloud': tag_cloud,
                                                          'front_images': front_images})


def draft_entry_detail(request, entry_id):

    if not request.user.is_authenticated():
        raise PermissionDenied

    entry = get_object_or_404(Entry, pk=entry_id)

    tag_cloud = build_tag_cloud()
    latest_entries = Entry.objects.filter(status=Entry.PUBLISHED_STATUS).order_by('creation_date')
    return render(request, 'techblog/entry_detail.html', {'entry':entry,
                                                          'latest_entries': latest_entries,
                                                          'tag_cloud': tag_cloud})


def about(request):
    return render(request, 'techblog/about.html')


def authors(request):

    authors_list = Smurf.objects.all()

    return render(request, 'techblog/authors.html', {'authors': authors_list})

techblog/templates/techblog/entry_detail.html
{% extends "techblog/base/base.html" %}
{% load staticfiles %}

{{% block  meta %}

                    <!--
    ************************************************************************
    *
    *                       HTTP META
    *
    ************************************************************************ -->

    <meta charset="UTF-8">
    <meta name="description" content="{{ entry.meta_description }}">
    <meta name="keywords" content="{{ entry.tags.names|join:', ' }}, {{ entry.seo_keywords|join:', ' }}">
    <meta name="author" content="{% for author in entry.authors %} {{ author.first_name }} {{ author.last_name }}, {% endfor %}">

                <!--
    ************************************************************************
    *
    *                       FACEBOOK META
    *
    ************************************************************************ -->
    <meta property="og:title" content="{{ entry.title }}" />
    <meta property="og:site_name" content="itsmurfs"/>
    <meta property="og:url" content="{{ request.build_absolute_uri}}" />
    <meta property="og:description" content="{{ entry.meta_description }}"/>
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" />            <!-- Default -->
    <meta property="fb:app_id" content="{{ FB_APP_ID }}" />
    {% comment %} TODO Add facebook information in the smurfs profile
    <meta property="article:author" content="https://www.facebook.com/fareedzakaria" />
    {% endcomment %}
    <meta property="og:image" content="{{ front_images.facebook }}" />

    <!--
    ************************************************************************
    *
    *                       TWITTER META
    *
    ************************************************************************ -->

    <meta name="twitter:card" content="summary_large_image">
{#<meta name="twitter:site" content="@nytimes">#}
<meta name="twitter:creator" content="@itsmurfs_"> {# TODO move inside a model #}
<meta name="twitter:title" content="{{ entry.title }}">
<meta name="twitter:description" content="{{ entry.meta_description }}">
<meta name="twitter:image:src" content="{{ front_images.facebook }}"> {# TODO change in twitter #}

{% endblock %}

{% block script %}

    {{ block.super }}


{% endblock %}

{{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'techblog/css/pygments_highlight.css' %}">
    <link rel="stylesheet" href="{% static 'techblog/css/entry_detail.css' %}">
    <link rel="stylesheet" href="{% static 'techblog/css/tag_cloud.css' %}">
{% endblock %}


{% block title %}

    {{ entry.title }} {# TODO add blog name #}

{% endblock %}

{{% block content %}

    <div class="blog-post">

        <h1 id="id_title" class="blog-post-title">
            {{ entry.title }}
        </h1>

        <p class="blog-post-meta">{{ entry.creation_date }} by <a href="{% url 'authors' %}">{{ entry.authors|join:" ," }}</a></p>

        <p id="id_meta_description" class="lead entry-description">
            "{{ entry.meta_description }}"
        </p>

        <hr>

    <div class="entry-content">
        {% autoescape off %}
            <!--
    ************************************************************************
    *
    *                       CONTENT
    *
    ************************************************************************ -->

            {{ entry.content }}
        {% endautoescape %}
    </div>

        <hr>

        <!--
    ************************************************************************
    *
    *                       References
    *
    ************************************************************************ -->
        {% if entry.has_references %}
            <div id="references_id">
                <h4> References </h4>
                <ul>
                    {% for ref in entry.references %}

                        {% if ref.link %}

                            <li><a href="{{ ref.link }}">{{ ref.title }}</a>
                                {% if ref.description %} - <i>{{ ref.description }}</i> {% endif %}
                            </li>

                        {% endif %}
                    {% endfor %}
                </ul>

            </div>
        {% endif %}

    <hr>

    {% block entry_tags %}
        {% comment %}This block is overriden in the draft entry detail renderization
        since a drafted entry doesn't have tags object{% endcomment %}
    <!--
    ************************************************************************
    *
    *                       Tags
    *
    ************************************************************************ -->

    {% include "techblog/include/entry_tags_block.html" with tags=entry.tags_list%}

    {% endblock %}


    </div>

{% endblock %}

{% block right_content %}

    {{ block.super }}

    {% if entry.git_link %}
    <!--
    ************************************************************************
*
*                       Git Url
*
************************************************************************ -->

    {% include "techblog/include/git_repo_block.html" with git_link=entry.git_link%}
{% endif %}

        {% if entry.demo_attachment %}
    <!--
    ************************************************************************
*
*                       Demo Attachment
*
************************************************************************ -->
{% include "techblog/include/download_block.html" with demo_attachment=entry.demo_attachment%}

{% endif %}

    <!--
************************************************************************
*
*                       Latest post
*
************************************************************************ -->

{% include "techblog/include/entry_list_block.html" with Title="Latest Posts" entries=latest_entries%}


    <!--
************************************************************************
*
*                       Related post
*
************************************************************************ -->

{% include "techblog/include/entry_list_block.html" with Title="Related Posts" entries=entry.similar_entries|slice:":3"%}
    <!--
************************************************************************
*
*                       Tag Cloud
*
************************************************************************ -->
{% include "techblog/include/tag_cloud_block.html" with tag_cloud=tag_cloud%}


{% endblock %}

{% block about %}

    <!--
    ************************************************************************
    *
    *                           Author block
    *
    ************************************************************************ -->

{%  for author in entry.authors %}
{% include "techblog/include/author_block.html" with author=author %}

    <hr>
    {% endfor %}

{% endblock %}

{% block bottom_content %}


    <hr>


    <!--
    ************************************************************************
    *
    *                       DISQUS
    *
    ************************************************************************ -->

    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'itsmurfs-techblog'; // required: replace example with your forum shortname
        var disqus_identifier = '{{ entry.id }}'; // a unique identifier for each page where Disqus is present
        var disqus_title = '{{ entry.title }}'; //a unique title for each page where Disqus is present
        var disqus_url = '{{ request.build_absolute_uri}}'; //a unique URL for each page where Disqus is present


        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function () {
            var dsq = document.createElement('script');
            dsq.type = 'text/javascript';
            dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


{% endblock %}

techblog/templates/techblog/home.html
{% extends 'techblog/base/base.html' %}
{% load staticfiles %}

{{% block  meta %}

    <!--
************************************************************************
*
*                       HTTP META
*
************************************************************************ -->

    <meta charset="UTF-8">
    <meta name="description" content="The itsmurfs blog!">
    <meta name="keywords" content="python django cloud mongodb nonrel postgres developer system">
    <meta name="author"
          content="{% for author in authors %} {{ author.first_name }} {{ author.last_name }}, {% endfor %}">

    <!--
************************************************************************
*
*                       FACEBOOK META
*
************************************************************************ -->
    <meta property="og:title" content="itsmurfs blog's home"/>
    <meta property="og:site_name" content="itsmurfs"/>
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:description" content=""/>
    <meta property="og:locale" content="en_US"/>            <!-- Default -->
    <meta property="fb:app_id" content="{{ FB_APP_ID }}"/>
    {% comment %} TODO Add facebook information in the smurfs profile
    {% endcomment %}
    <meta property="og:image" content="{% static 'itsmurfs_techblog/images/itsmurfs_logos.png' %}"/>

    <!--
    ************************************************************************
    *
    *                       TWITTER META
    *
    ************************************************************************ -->

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:creator" content="@itsmurfs_"> {# TODO move inside a model #}
    <meta name="twitter:title" content="itsmurfs blog's home">
    <meta name="twitter:description" content="The itsmurfs blog!">
    <meta name="twitter:image:src" content="{% static 'itsmurfs_techblog/images/itsmurfs_logos.png' %}">

{% endblock %}

{{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'techblog/css/tag_cloud.css' %}">
{% endblock %}


{% block about %}

    <h4><strong>Authors</strong></h4>
    {% for author in authors %}
        {% include "techblog/include/author_block.html" with author=author %}

        <hr>
    {% endfor %}

{% endblock %}

{% block right_content %}

    {{ block.super }}

    <!--
************************************************************************
*
*                       Tag Cloud
*
************************************************************************ -->
    {% include "techblog/include/tag_cloud_block.html" with tag_cloud=tag_cloud %}
{% endblock %}


{% block content %}

    {% if paginated_entries.object_list %}
        {% for entry in paginated_entries.object_list %}

            <h2 class="blog-post-title">
                {{ entry.title }}
            </h2>
            {# TODO Subtitle???? #}

            <p class="blog-post-meta">{{ entry.creation_date }} by <a href="#">{{ entry.authors|join:", " }}</a></p>

            <p id="id_meta_description" class="lead entry-description">
                "{{ entry.meta_description }}"
            </p>


            <a href="{% url 'entry_detail' entry.id entry.slug %}"> continue reading --></a>

            <hr>

        {% endfor %}
    {% else %}

        <h3><i>No posts yet :(</i></h3>
    {% endif %}

{% endblock %}

{% block bottom_content %}

    <ul class="pager"> <!-- Bootstrap pager -->

        {# https://docs.djangoproject.com/en/dev/topics/pagination/ #}
        {% if paginated_entries.has_previous %}
            <li><a href="?page={{ paginated_entries.previous_page_number }}">Previous</a></li>
        {% endif %}

        <li>
            <span>
            Page {{ paginated_entries.number }} of {{ paginated_entries.paginator.num_pages }}.
        </span>
        </li>

        {% if paginated_entries.has_next %}
            <li><a href="?page={{ paginated_entries.next_page_number }}">Next</a></li>
        {% endif %}

    </ul>


{% endblock %}